name: Build Kivy Android APK

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify a Python version compatible with Kivy/Buildozer

    - name: Install Buildozer and Cython
      # Cython is a build dependency required by Buildozer for compilation.
      run: pip install buildozer cython

    - name: Install system dependencies for Buildozer
      # These are Linux packages required by Buildozer for Android compilation
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libssl-dev libffi-dev libsqlite3-dev liblzma-dev libbz2-dev

    - name: Build Android Debug APK
      # This is the core Buildozer command.
      # The first time this runs, it will download Android SDK, NDK, etc., which takes time.
      # Subsequent runs will be faster due to caching.
      run: buildozer android debug

    - name: Upload APK artifact
      # This step uploads the generated APK as a workflow artifact,
      # which you can download from the GitHub Actions run page.
      uses: actions/upload-artifact@v4
      with:
        name: FaceApp-APK
        path: bin/*.apk # The APK will be in the 'bin' directory created by Buildozer
        retention-days: 7 # How long to keep the artifact available for download
